### PR TITLE
Add Always Right Institute.

### PR DESCRIPTION
**Pull request by sgade**
Add the feed for the always right institute.

The [action for this commit](https://github.com/sgade/feeds/commit/40f9fab2d01728c332bb0c50f2e35949e2fadd53/checks?check_suite_id=376641323) was run on my repo already.

### CODE REVIEW

**Comment by sgade** [comment]
The GitHub Action was triggered! Seems to work now. 👌

**Comment by sgade** [comment]
> The [GitHub Action](https://github.com/SwiftBlogs/feeds/commit/40f9fab2d01728c332bb0c50f2e35949e2fadd53/checks?check_suite_id=376643246) was triggered! Seems to work now. 👌

Now that is weird. Locally and in my repository, the ValidatorCLI has no problems with the changes. On this repo, it seems there is an `l` missing for `feeds.xml`, or something of the kind. Might be related to the internal parsing of some feed?

Error message is the following:
```
Start Validation ...
Validating JSON file './feeds.json' ...
Found 35 feed(s).
feedParser(FeedKit.ParserError.internalError(reason: "The file “feed.xm” couldn’t be opened."))
##[error]Process completed with exit code 1.
```

**Comment by sgade** [comment]
@JulianKahnert Still a broken check.

Did you change something about the action in comparison to my fork? 56e1db7 fails here, but [works in my repo](https://github.com/sgade/feeds/runs/366844052).

**Comment by JulianKahnert** [comment]
Hi @sgade, I found the bug, but had no time to fix it.


https://github.com/SwiftBlogs/feeds/blob/011f45b954f000006a125faf814de32cca227ac3/Sources/DetailedFeed/DetailedFeedValidator.swift#L44

The `dropLast(2)` removes the last L of the URL. Thats why the feed is broken. A solution would be a regex that fetches only the after `”feed”:` and between the `”`. But I had no time to fix this.

Your repo works because the commit is on the master branch and the validation stage is a diff between the current branch and the master.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sgade** [comment]
Now I understand the problem. I guess you want to avoid long validation times, once the feed.json grows even more. However, I would expect validations always run on the same dataset. That said, when I change a feed that change does not get validated yet, which might pose problems in the future.

Checking with a regex would be nice. I changed the line so that it only drop the last quotation mark:
```swift
let rawFeed = String(trimmedLine.replacingOccurrences(of: "\"feed\": \"", with: "").dropLast(1))
```

Using `dropLast(1)` [seems to work](https://github.com/SwiftBlogs/feeds/pull/6/checks?check_run_id=367661102).

**Comment by sgade** [comment]
As we discussed, using `dropLast(1)` does not remove trailing commas that are present when defining other fields.

Instead of using complicated RegularExpressions (that did not seems to work even when using [complex ones](https://urlregex.com)) I decided to simply search for the last `"` character in the string and create a substring right up until that index. This way, any characters after are removed, too. See https://github.com/SwiftBlogs/feeds/commit/4689454d13457d616ae2ba43febf85fdfb1cbdfa.

If there is an error in the URL, the behaviour is as previous: the constructor returns `nil` and the URL is silently ignored during validation. So here is another idea:
How about returning an array of `Result` from the `getFeed` function? That way we could show an `.invalidURL` error case while being able to continue with the URLs that did pass validation successfully.

**Comment by JulianKahnert** [comment]
That looks very good!  ☺️☺️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
